pipeline {
    agent any

    tools {
        jdk 'java-11'       // Make sure 'java-11' is configured in Jenkins
        maven 'maven'       // Make sure 'maven' is configured in Jenkins
    }

    stages {
        stage('Git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/test-1.git'
            }
        }

        stage('Compile') {
            steps {
                sh "mvn compile"
            }
        }

        stage('Build') {
            steps {
                sh "mvn clean install"
            }
        }

        stage('Code Scan') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh """
                        mvn sonar:sonar \
                        -Dsonar.login=$SONAR_AUTH_TOKEN \
                        -Dsonar.host.url=http://54.196.167.245:9000/
                    """
                }
            }
        }

        stage('Build and Tag Docker Image') {
            steps {
                sh "docker build -t akhila792/webapp:1 ."
            }
        }

        stage('Docker Image Scan') {
            steps {
                sh "trivy image --format table -o trivy-image-report.html akhila792/webapp:1"
            }
        }

        stage('Containerization') {
            steps {
                sh '''
                    docker stop c3 || true
                    docker rm c3 || true
                    docker run -it -d --name c3 -p 9004:8080 akhila792/webapp:1
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                sh "docker push akhila792/webapp:1"
            }
        }
    }
}
